<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBevGs3I\EccubeEccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBevGs3I/EccubeEccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBevGs3I.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBevGs3I\EccubeEccube_KernelDevDebugContainer::class, EccubeEccube_KernelDevDebugContainer::class, false);
}

return new \ContainerBevGs3I\EccubeEccube_KernelDevDebugContainer([
    'container.build_hash' => 'BevGs3I',
    'container.build_id' => '832f0039',
    'container.build_time' => 1729564483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBevGs3I');
