<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ZwecOQ\EccubeEccube_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ZwecOQ/EccubeEccube_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container5ZwecOQ.legacy');

    return;
}

if (!\class_exists(EccubeEccube_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container5ZwecOQ\EccubeEccube_KernelProdDebugContainer::class, EccubeEccube_KernelProdDebugContainer::class, false);
}

return new \Container5ZwecOQ\EccubeEccube_KernelProdDebugContainer([
    'container.build_hash' => '5ZwecOQ',
    'container.build_id' => 'bad9a28f',
    'container.build_time' => 1745038228,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ZwecOQ');
